apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: fib
  labels:
    app: fib
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fib
  template:
    metadata:
      labels:
        app: fib
    spec:
      containers:
      - name: fib
        image: errm/fib
        ports:
        - containerPort: 9292
